/* Generated by tex3ds */
#pragma once

#define sprites_emptytile_idx 0
#define sprites_point_idx 1
#define sprites_good_idx 2
#define sprites_bad_idx 3
#define sprites_spikes_idx 4
#define sprites_ugly_idx 5
#define sprites_enemy_idx 6
#define sprites_selectedtile_idx 7
#define sprites_watertile_idx 8
