/* Generated by tex3ds */
#pragma once

#define uisprites_none_idx 0
#define uisprites_good_idx 1
#define uisprites_star_idx 2
#define uisprites_button_cpad_idx 3
#define uisprites_button_dpad_idx 4
#define uisprites_button_dpadup_idx 5
#define uisprites_button_dpaddown_idx 6
#define uisprites_button_dpadleft_idx 7
#define uisprites_button_dpadright_idx 8
#define uisprites_button_L_idx 9
#define uisprites_button_R_idx 10
#define uisprites_panelbase_idx 11
